name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # Cambiado a una versión más reciente de Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Start services
        run: scripts/start_services.sh

      - name: Run test suite
        run: docker compose -f docker/docker-compose.yaml exec -T app bash scripts/build.sh

      - name: Upload coverage report
        uses: codecov/codecov-action@v2

